# Generated by Django 5.0.7 on 2024-09-20 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField(max_length=8)),
                ('humidity', models.FloatField(max_length=8)),
                ('time', models.TimeField()),
            ],
        ),
    ]
