# Generated by Django 5.0.7 on 2024-09-21 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='time',
            field=models.DateField(),
        ),
    ]
