# Generated by Django 5.0.7 on 2024-09-21 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_information_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
